window.lesson02={
id:"s3",title:"Publica el Ebook con Amazon S3",navTitle:"02 · Amazon S3",
hero:{eyebrow:"BLOQUE 02 · AMAZON S3",title:"De una web comprobada a un sitio alojado en AWS",description:"Verificamos primero el frontend con GitHub Pages y después creamos, llenamos y configuramos S3 desde AWS CLI.",chips:["GitHub Pages","S3","AWS CLI","Bucket","Objetos","Website hosting"]},
sections:[
{type:"concept",title:"Antes de hablar de S3 necesitamos tener una web",text:"No vamos a escribir aws s3 sync sobre una carpeta imaginaria. Primero obtendrás la aplicación Ebook desde nuestro repositorio del curso, comprobarás que existe y funciona, la publicarás en GitHub Pages y sólo después subirás ESA MISMA aplicación a S3."},
{type:"wizard",label:"PREPARA LA APLICACIÓN",title:"Obtén el Ebook antes de entrar en AWS",steps:[
{title:"Sitúate en tu carpeta de trabajo",learn:"git clone crea una copia local completa de un repositorio. Antes de clonar conviene saber dónde se va a crear.",text:"Abre Git Bash y sitúate en una carpeta de trabajo que puedas localizar después. Para simplificar, puedes empezar en tu carpeta personal.",code:"cd ~\npwd",expected:"pwd muestra tu carpeta personal de Git Bash, normalmente relacionada con C:\\Users\\TU_USUARIO.",success:"Ya sabes dónde se creará la carpeta Serverless.",help:[["No entiendo la ruta","En Git Bash /c/Users/alumno equivale a C:\\Users\\alumno en Windows."],["Quiero otra carpeta","Puedes usar cd para ir a ella antes de clonar. Lo importante es recordar dónde estás."]],check:"Debes saber en qué carpeta estás antes de ejecutar clone."},
{title:"Clona nuestro repositorio",learn:"No clonamos ahora el repositorio externo de referencia. El material que utilizaremos en clase estará centralizado en nuestro repositorio Serverless.",text:"Clona el repositorio del curso.",code:"git clone https://github.com/albertohdezakkari/Serverless.git",expected:"Git muestra mensajes de clonación y aparece una nueva carpeta llamada Serverless.",success:"Ya tienes una copia local del cuaderno y de los recursos del laboratorio.",help:[["destination path 'Serverless' already exists","Probablemente ya lo clonaste. No vuelvas a clonarlo encima. Entra con cd Serverless y actualízalo con git pull."],["Authentication failed","Comprueba gh auth status y que puedes acceder a GitHub. El repo es público, por lo que normalmente HTTPS no debería requerir autenticación para leer."],["git: command not found","Vuelve al Bloque 00: Git todavía no está preparado."]],check:"La carpeta Serverless debe existir localmente."},
{title:"Entra en el repositorio",learn:"cd significa change directory. A partir de ahora muchos comandos dependen de la carpeta actual, así que siempre debemos saber dónde estamos.",text:"Entra en Serverless y observa su contenido.",code:"cd Serverless\npwd\nls",expected:"pwd termina en /Serverless y ls muestra los archivos/carpetas del repositorio.",success:"Estás dentro de nuestra copia local del repositorio.",help:[["No such file or directory","Comprueba con ls si realmente se creó Serverless y revisa desde qué carpeta ejecutaste clone."],["Ya estaba clonado","Dentro de Serverless ejecuta git pull para traer la versión más reciente antes de continuar."]],check:"pwd debe confirmar que estás dentro de Serverless."},
{title:"Localiza la aplicación Ebook",learn:"El repositorio contiene DOS webs diferentes: el cuaderno de aprendizaje y la aplicación Ebook que desplegaremos. No debemos confundirlas.",text:"Entra en la carpeta del laboratorio.",code:"cd lab/ebook-web\npwd\nls",expected:"La ruta termina en /Serverless/lab/ebook-web y debes encontrar index.html junto con sus recursos (css, js, images...).",success:"ÉSTA es la aplicación que utilizaremos en GitHub Pages y después en S3.",help:[["No existe lab/ebook-web","Primero ejecuta git pull desde la raíz de Serverless. Si sigue sin existir, no continúes: falta el recurso del laboratorio."],["Veo el index.html del cuaderno","Comprueba pwd. Debes estar dentro de lab/ebook-web, no en la raíz Serverless."]],check:"No continúes hasta identificar index.html de la aplicación Ebook."},
{title:"Comprueba la web antes de publicar",learn:"Antes de AWS queremos demostrar que los archivos forman una web válida. Así, si S3 falla después, sabemos que el problema no era el frontend de partida.",text:"Abre index.html en el navegador desde el Explorador de Windows o utiliza la forma de previsualización que indiquemos en clase. Recorre la página y comprueba que estilos e imágenes cargan.",expected:"Ves la landing page del Ebook con estilos e imágenes, no HTML sin formato.",success:"La aplicación base funciona localmente. Ya podemos publicarla.",help:[["Se ve sin estilos","Comprueba que css, js, images y fonts están junto a index.html conservando la estructura."],["Faltan imágenes","No copies sólo index.html: necesitamos la carpeta completa ebook-web."]],check:"La web debe verse correctamente antes de GitHub Pages."}
]},
{type:"flow",title:"Recorrido del bloque",items:["Clona Serverless","lab/ebook-web","Comprueba local","GitHub Pages ✓","AWS Academy","AWS CLI","S3","Website endpoint"]},
{type:"tabs",label:"PUBLICA ANTES DE AWS",title:"GitHub Pages · nuestra primera publicación",tabs:[
{title:"① Por qué primero Pages",intro:"GitHub Pages nos sirve como checkpoint: demuestra que la web puede publicarse correctamente antes de introducir S3. Si aquí ya falla, no culpamos a AWS.",flow:["lab/ebook-web local ✓","GitHub","GitHub Pages","URL pública ✓","Después → S3"]},
{title:"② Importante · Pages y subcarpetas",intro:"Nuestro repositorio principal ya publica el CUADERNO desde la raíz. La aplicación Ebook está en una subcarpeta. No vamos a cambiar Pages del repo principal y romper el cuaderno.",note:"Para los alumnos, prepararemos un repositorio/copia de trabajo de la aplicación o un procedimiento de publicación que mantenga separado el cuaderno de la web Ebook. La regla es: primero URL pública del Ebook; después S3."},
{title:"③ Evidencia antes de S3",intro:"Antes de crear el bucket debes poder responder sí a estas preguntas.",steps:[["Local","¿La web se ve correctamente desde tu copia?"],["Git","¿Sabes qué carpeta contiene realmente el Ebook?"],["Publicación","¿Tienes una URL pública de GitHub Pages para el Ebook?"],["Separación","¿Entiendes que esa web es distinta del cuaderno Serverless?"]]}
]},
{type:"concept",title:"CONCEPTO NUEVO · Bucket y objeto",text:"Un bucket es un contenedor lógico de S3. index.html, CSS, JavaScript e imágenes son objetos. El nombre del bucket debe ser válido y globalmente único."},
{type:"warning",title:"Antes de S3: verifica Academy",text:"Ejecuta aws sts get-caller-identity. Si falla, renueva las credenciales. Una sesión caducada no es un error de S3."},
{type:"tabs",label:"AWS ACADEMY · TE AYUDAMOS A ELEGIR",title:"Descubre tu región antes de crear el bucket",tabs:[
{title:"① Comprueba Academy",intro:"Antes de crear nada confirma que las credenciales temporales siguen funcionando.",code:"aws sts get-caller-identity",note:"Si falla, vuelve al Learning Lab y renueva/revisa las credenciales antes de continuar."},
{title:"② Mira tu región",intro:"Ahora pregunta a AWS CLI qué región tiene configurada tu perfil.",code:"aws configure get region",steps:[["Si aparece una región","Guárdala: la utilizaremos en el siguiente comando."],["Lo más habitual en Academy","En muchos laboratorios docentes puedes encontrarte con us-east-1 (N. Virginia) o us-west-2, pero NO lo damos por supuesto: manda lo que devuelva tu entorno."],["Si no aparece nada","No inventes una región. Comprueba la región indicada por tu Learning Lab/consola y configúrala o úsala explícitamente en los comandos."]]},
{title:"③ Entiende el nombre",intro:"Los nombres de buckets S3 deben ser únicos en el espacio de nombres correspondiente. Un nombre sencillo como ebook probablemente ya exista.",steps:[["Usa un patrón","Por ejemplo: ebook-serverless-alberto-2026 o ebook-serverless-a01-2026."],["Minúsculas","Trabaja con minúsculas, números y guiones para evitar problemas."],["Si ya existe","Cambia el sufijo. No es un fallo de AWS Academy: el nombre está ocupado."]]},
{title:"④ Si es us-east-1",intro:"US East (N. Virginia) es el caso especial. AWS permite crear el bucket sin LocationConstraint.",code:"aws s3api create-bucket \\\n  --bucket NOMBRE-UNICO \\\n  --region us-east-1\n\naws s3 ls",note:"Si tu región REAL es us-east-1, utiliza este camino."},
{title:"⑤ Si es otra región",intro:"Para regiones distintas de us-east-1, AWS requiere indicar también LocationConstraint con esa misma región.",code:"aws s3api create-bucket \\\n  --bucket NOMBRE-UNICO \\\n  --region TU-REGION \\\n  --create-bucket-configuration LocationConstraint=TU-REGION\n\naws s3 ls",note:"Ejemplo: si aws configure get region devuelve us-west-2, sustituye las DOS apariciones de TU-REGION por us-west-2."},
{title:"⑥ Si falla",intro:"Interpreta el error antes de cambiar cosas.",steps:[["BucketAlreadyExists / nombre ocupado","Elige otro nombre único y repite."],["InvalidLocationConstraint","Revisa la región. Recuerda que us-east-1 es el caso especial."],["AccessDenied","Comprueba que estás en Learning Lab, que las credenciales no han caducado y que Academy permite s3:CreateBucket."],["ExpiredToken","Renueva las credenciales temporales de Academy."],["Could not connect / región extraña","Comprueba aws configure get region y la región del laboratorio."]]}
]},
{type:"concept",title:"2 · Bucket creado ≠ bucket con contenido",text:"Ahora sincronizamos nuestra carpeta web. aws s3 sync compara origen y destino y sube lo necesario."},
{type:"code",label:"DESDE LA RAÍZ DEL PROYECTO",title:"Sincroniza la web",code:"# Si estás dentro de Serverless/lab/ebook-web:\naws s3 sync ./ s3://NOMBRE-BUCKET\n\n# Después comprueba:\naws s3 ls s3://NOMBRE-BUCKET"},
{type:"concept",title:"3 · Archivos en S3 ≠ website configurado",text:"Website hosting es otra configuración. Debemos indicar al menos qué documento funciona como índice."},
{type:"code",label:"AWS CLI",title:"Configura el website",code:"aws s3 website s3://NOMBRE-BUCKET/ \\\n  --index-document index.html \\\n  --error-document error.html"},
{type:"warning",title:"4 · Acceso público: punto sensible",text:"El website clásico de S3 necesita lectura pública de los objetos. S3 bloquea acceso público por defecto. AWS recomienda mantener ese bloqueo y, en producción, usar arquitecturas más seguras. En Academy sólo realizaremos las operaciones permitidas por el laboratorio; no intentaremos saltarnos restricciones IAM."},
{type:"concept",title:"Qué estamos aprendiendo realmente",text:"Almacenamiento, website configuration y permisos son tres responsabilidades diferentes. Que una funcione no demuestra las otras."},
{type:"checklist",title:"Checkpoint S3",items:["Academy está activo.","El bucket existe.","Los objetos están subidos.","index.html está presente.","Website hosting está configurado si Academy lo permite.","He comprobado el resultado.","Puedo explicar bucket, objeto, website y permisos."]},
{type:"quiz",title:"Comprueba",question:"Has subido index.html, pero la web no es accesible como sitio. ¿Qué conclusión es correcta?",options:["S3 está roto.","Subir objetos y configurar website/permisos son pasos diferentes.","Necesitamos DynamoDB.","Falta instalar Node.js."],correct:1,explanation:"Tener objetos almacenados no configura automáticamente website hosting ni acceso de lectura."},
{type:"success",title:"He aprendido",text:"Sé crear y verificar un bucket, sincronizar contenido y distinguir almacenamiento, website configuration y permisos."}
]};