window.lesson02={
id:"s3",title:"Publica el Ebook con Amazon S3",navTitle:"02 · Amazon S3",
hero:{eyebrow:"BLOQUE 02 · AMAZON S3",title:"De una web comprobada a un sitio alojado en AWS",description:"Verificamos primero el frontend con GitHub Pages y después creamos, llenamos y configuramos S3 desde AWS CLI.",chips:["GitHub Pages","S3","AWS CLI","Bucket","Objetos","Website hosting"]},
sections:[
{type:"concept",title:"Primero demostramos que el frontend funciona",text:"La web local se versiona en GitHub y puede publicarse con GitHub Pages. Así separamos dos problemas: frontend correcto y hosting AWS."},
{type:"flow",title:"Recorrido del bloque",items:["Web local","GitHub","GitHub Pages ✓","AWS Academy","AWS CLI","S3","Website endpoint"]},
{type:"concept",title:"CONCEPTO NUEVO · Bucket y objeto",text:"Un bucket es un contenedor lógico de S3. index.html, CSS, JavaScript e imágenes son objetos. El nombre del bucket debe ser válido y globalmente único."},
{type:"warning",title:"Antes de S3: verifica Academy",text:"Ejecuta aws sts get-caller-identity. Si falla, renueva las credenciales. Una sesión caducada no es un error de S3."},
{type:"tabs",label:"AWS ACADEMY · TE AYUDAMOS A ELEGIR",title:"Descubre tu región antes de crear el bucket",tabs:[
{title:"① Comprueba Academy",intro:"Antes de crear nada confirma que las credenciales temporales siguen funcionando.",code:"aws sts get-caller-identity",note:"Si falla, vuelve al Learning Lab y renueva/revisa las credenciales antes de continuar."},
{title:"② Mira tu región",intro:"Ahora pregunta a AWS CLI qué región tiene configurada tu perfil.",code:"aws configure get region",steps:[["Si aparece una región","Guárdala: la utilizaremos en el siguiente comando."],["Lo más habitual en Academy","En muchos laboratorios docentes puedes encontrarte con us-east-1 (N. Virginia) o us-west-2, pero NO lo damos por supuesto: manda lo que devuelva tu entorno."],["Si no aparece nada","No inventes una región. Comprueba la región indicada por tu Learning Lab/consola y configúrala o úsala explícitamente en los comandos."]]},
{title:"③ Entiende el nombre",intro:"Los nombres de buckets S3 deben ser únicos en el espacio de nombres correspondiente. Un nombre sencillo como ebook probablemente ya exista.",steps:[["Usa un patrón","Por ejemplo: ebook-serverless-alberto-2026 o ebook-serverless-a01-2026."],["Minúsculas","Trabaja con minúsculas, números y guiones para evitar problemas."],["Si ya existe","Cambia el sufijo. No es un fallo de AWS Academy: el nombre está ocupado."]]},
{title:"④ Si es us-east-1",intro:"US East (N. Virginia) es el caso especial. AWS permite crear el bucket sin LocationConstraint.",code:"aws s3api create-bucket \\\n  --bucket NOMBRE-UNICO \\\n  --region us-east-1\n\naws s3 ls",note:"Si tu región REAL es us-east-1, utiliza este camino."},
{title:"⑤ Si es otra región",intro:"Para regiones distintas de us-east-1, AWS requiere indicar también LocationConstraint con esa misma región.",code:"aws s3api create-bucket \\\n  --bucket NOMBRE-UNICO \\\n  --region TU-REGION \\\n  --create-bucket-configuration LocationConstraint=TU-REGION\n\naws s3 ls",note:"Ejemplo: si aws configure get region devuelve us-west-2, sustituye las DOS apariciones de TU-REGION por us-west-2."},
{title:"⑥ Si falla",intro:"Interpreta el error antes de cambiar cosas.",steps:[["BucketAlreadyExists / nombre ocupado","Elige otro nombre único y repite."],["InvalidLocationConstraint","Revisa la región. Recuerda que us-east-1 es el caso especial."],["AccessDenied","Comprueba que estás en Learning Lab, que las credenciales no han caducado y que Academy permite s3:CreateBucket."],["ExpiredToken","Renueva las credenciales temporales de Academy."],["Could not connect / región extraña","Comprueba aws configure get region y la región del laboratorio."]]}
]},
{type:"concept",title:"2 · Bucket creado ≠ bucket con contenido",text:"Ahora sincronizamos nuestra carpeta web. aws s3 sync compara origen y destino y sube lo necesario."},
{type:"code",label:"DESDE LA RAÍZ DEL PROYECTO",title:"Sincroniza la web",code:"aws s3 sync ./web s3://NOMBRE-BUCKET\n\naws s3 ls s3://NOMBRE-BUCKET"},
{type:"concept",title:"3 · Archivos en S3 ≠ website configurado",text:"Website hosting es otra configuración. Debemos indicar al menos qué documento funciona como índice."},
{type:"code",label:"AWS CLI",title:"Configura el website",code:"aws s3 website s3://NOMBRE-BUCKET/ \\\n  --index-document index.html \\\n  --error-document error.html"},
{type:"warning",title:"4 · Acceso público: punto sensible",text:"El website clásico de S3 necesita lectura pública de los objetos. S3 bloquea acceso público por defecto. AWS recomienda mantener ese bloqueo y, en producción, usar arquitecturas más seguras. En Academy sólo realizaremos las operaciones permitidas por el laboratorio; no intentaremos saltarnos restricciones IAM."},
{type:"concept",title:"Qué estamos aprendiendo realmente",text:"Almacenamiento, website configuration y permisos son tres responsabilidades diferentes. Que una funcione no demuestra las otras."},
{type:"checklist",title:"Checkpoint S3",items:["Academy está activo.","El bucket existe.","Los objetos están subidos.","index.html está presente.","Website hosting está configurado si Academy lo permite.","He comprobado el resultado.","Puedo explicar bucket, objeto, website y permisos."]},
{type:"quiz",title:"Comprueba",question:"Has subido index.html, pero la web no es accesible como sitio. ¿Qué conclusión es correcta?",options:["S3 está roto.","Subir objetos y configurar website/permisos son pasos diferentes.","Necesitamos DynamoDB.","Falta instalar Node.js."],correct:1,explanation:"Tener objetos almacenados no configura automáticamente website hosting ni acceso de lectura."},
{type:"success",title:"He aprendido",text:"Sé crear y verificar un bucket, sincronizar contenido y distinguir almacenamiento, website configuration y permisos."}
]};