window.lesson03={
id:"lambda",title:"Mi primera función Serverless con AWS Lambda",navTitle:"03 · Primera Lambda",
hero:{eyebrow:"BLOQUE 03 · PRIMER BACKEND SERVERLESS",title:"Crea tu primera Lambda desde AWS Academy",description:"La primera vez trabajamos desde la consola y sin correr: concepto, runtime, Execution Role, código, Deploy, Test Event y CloudWatch.",chips:["Lambda","Node.js","Execution Role","event","handler","CloudWatch"]},
sections:[
{type:"flow",title:"Recorrido del bloque · antes de empezar",items:["A · ENTIENDE · Lambda → Function/Invocation → handler/event → Execution Role","B · CREA · Learner Lab → función → Node.js → role","C · PROGRAMA · index.mjs completo → Deploy","D · PRUEBA · Test Event → respuesta","E · OBSERVA · CloudWatch → AWS CLI → checkpoint ✓"]},
{type:"concept",title:"Objetivo del Bloque 03",text:"Crear tu primer backend serverless y poder explicar qué ejecuta Lambda, qué recibe, con qué permisos trabaja, cómo la invocas y dónde observas lo ocurrido."},
{type:"concept",title:"Conexión con S3",text:"S3 ALOJA nuestra web. Lambda PROCESARÁ información. Todavía no conectamos formulario ni API Gateway: primero aislamos Lambda para aprenderla sin mezclar problemas."},
{type:"tabs",label:"A · FUNDAMENTOS",title:"Entiende Lambda antes de crearla",tabs:[
{title:"① ¿Por qué Lambda?",intro:"Necesitamos ejecutar lógica backend cuando ocurra un evento sin administrar directamente un servidor Node.js.",flow:["Evento","Lambda","Código Node.js","Respuesta"]},
{title:"② Function / Invocation",intro:"Function es el recurso que creas. Invocation es UNA ejecución concreta de esa Function."},
{title:"③ handler / event",intro:"handler es el punto de entrada que Lambda ejecuta. event contiene los datos recibidos en esa invocación.",code:"export const handler = async (event) => {\n  // event = datos recibidos\n};"},
{title:"④ Runtime",intro:"Runtime es el entorno que ejecuta tu código. Trabajaremos con JavaScript/Node.js. AWS documenta actualmente Node.js 24.x para nuevas funciones; si Learner Lab ofrece otra versión Node.js soportada definida para clase, usamos esa."},
{title:"⑤ Execution Role",intro:"Lambda necesita SU propia identidad para actuar sobre AWS. No es lo mismo que tus credenciales temporales de Academy.",flow:["TÚ → credenciales Learner Lab","LAMBDA → Execution Role","Role → permisos CloudWatch / después DynamoDB y SNS"],note:"En Learner Lab usaremos el role existente que el laboratorio permita; no crearemos privilegios administrativos por nuestra cuenta."}
]},
{type:"wizard",label:"B · CREA LA FUNCIÓN",title:"Crea ebook-contact desde AWS Academy",steps:[
{shortTitle:"Academy",title:"Entra desde Learner Lab",learn:"La consola debe abrirse desde el laboratorio para trabajar con su cuenta temporal.",text:"Start Lab → AWS Console → busca Lambda → Functions.",expected:"Ves Lambda → Functions dentro del Learner Lab.",success:"Servicio y cuenta correctos.",help:[["Lab parado","Start Lab y espera."],["Dudas de identidad","En Git Bash: aws sts get-caller-identity."]],check:"No pulses Create function fuera del Learner Lab."},
{shortTitle:"Create",title:"Author from scratch",learn:"Crearemos una Function nueva y escribiremos nuestro propio código.",text:"Create function → Author from scratch → Function name: ebook-contact.",expected:"Basic information muestra ebook-contact.",success:"Nombre fijado para toda la práctica.",help:[["Ya existe","Abre la existente o sigue la indicación del profesor; no crees copias al azar."]],check:"Function name = ebook-contact."},
{shortTitle:"Runtime",title:"Node.js + x86_64",learn:"Runtime decide qué ejecuta nuestro JavaScript; Architecture define la CPU.",text:"Selecciona Node.js 24.x si está disponible y mantén x86_64.",expected:"Runtime Node.js y Architecture x86_64.",success:"Entorno de ejecución definido.",help:[["No aparece 24.x","Usa la versión Node.js soportada indicada para clase; Node.js 22.x sigue soportado actualmente."],["¿arm64?","No es incorrecto; mantenemos x86_64 para reducir variables en la primera práctica."]],check:"No uses Python: este cuaderno trabaja con Node.js."},
{shortTitle:"Role",title:"Execution Role · detente aquí",learn:"Tus credenciales Academy autorizan TUS acciones. Cuando Lambda se ejecute necesitará SU identidad: el Execution Role.",text:"Expande Permissions / Change default execution role. En Learner Lab utiliza el role existente permitido por el laboratorio, habitualmente LabRole o el equivalente que aparezca disponible. No crees AdministratorAccess.",expected:"Puedes identificar el role que Lambda utilizará.",success:"Sabes con qué identidad se ejecutará ebook-contact.",help:[["No aparece LabRole","No inventes un nombre. Revisa los roles existentes que Academy permite seleccionar y sigue el indicado para el laboratorio."],["No puedo crear role","Es habitual en Academy; usa el role existente permitido."],["AccessDenied / PassRole","Es un problema de permisos/role, no del código JavaScript."]],check:"Responde antes de avanzar: ¿qué identidad usará Lambda cuando se invoque?"},
{shortTitle:"Crear",title:"Create function y oriéntate",learn:"Crear el recurso no demuestra todavía que nuestro código funcione.",text:"Pulsa Create function. Después localiza Code, Test, Configuration y Monitor.",expected:"Ves ebook-contact y puedes señalar esas cuatro zonas.",success:"Function creada; ahora podremos programarla.",help:[["Create falla","Si menciona IAM/PassRole/AccessDenied vuelve al paso Role."],["Tarda","Espera a que AWS termine antes de editar."]],check:"No pegues código hasta orientarte en la pantalla."}
]},
{type:"consolemap",label:"MAPA DE REFERENCIA · NO ES INTERACTIVO",title:"Reconoce las cuatro zonas de tu función Lambda",text:"Este cuadro no se pulsa. Es una chuleta visual para que puedas orientarte cuando trabajemos en la consola AWS. Busca estas mismas zonas en tu pantalla real de ebook-contact.",service:"Lambda › Functions › ebook-contact",areas:[
{title:"Code · LO USAREMOS AHORA",text:"Aquí encontrarás index.mjs, pegarás el código y pulsarás Deploy."},
{title:"Test · LO USAREMOS DESPUÉS",text:"Aquí crearemos primer-evento y provocaremos nuestra primera invocación."},
{title:"Configuration · PERMISOS/AJUSTES",text:"Aquí volveremos cuando necesitemos revisar configuración y el Execution Role."},
{title:"Monitor · AL FINAL",text:"Aquí observaremos ejecuciones y accederemos a CloudWatch Logs."}
]},
{type:"checklist",title:"STOP · Antes de programar",items:["Estoy dentro del Learning Lab correcto.","Veo la función ebook-contact.","El runtime es Node.js.","La arquitectura es x86_64.","He identificado el Execution Role utilizado."]},
{type:"codelearning",label:"C · PROGRAMA",title:"Lee y comprende index.mjs de arriba abajo",filename:"index.mjs",text:"No memorices líneas aisladas. Lee primero los comentarios: te cuentan la historia completa de una invocación. Después observa el código que hay justo debajo de cada explicación.",code:"// LAMBDA ejecutará esta función cada vez que se produzca una invocación.\n// export = Lambda puede encontrarla · async = podremos usar await más adelante.\n// event = objeto con los datos recibidos en ESTA invocación.\nexport const handler = async (event) => {\n\n  // Dejamos una evidencia de los datos recibidos.\n  // Este mensaje lo podremos localizar después en CloudWatch Logs.\n  console.log('Evento recibido:', event);\n\n  // Intentamos leer la propiedad nombre del event.\n  // ?? significa: si nombre es null/undefined, utiliza 'usuario'.\n  const nombre = event.nombre ?? 'usuario';\n\n  // return devuelve el resultado de esta invocación.\n  // statusCode 200 representa que la operación ha ido correctamente.\n  return {\n    statusCode: 200,\n\n    // body será el contenido de la respuesta.\n    // JSON.stringify convierte el objeto JavaScript en texto JSON.\n    body: JSON.stringify({\n      // Si event.nombre era María → Hola María. Tu Lambda funciona.\n      message: 'Hola ' + nombre + '. Tu Lambda funciona.'\n    })\n  };\n};",after:{title:"ANTES DE COPIAR · predice",text:"Si el Test Event contiene { nombre: 'María' }, deberías poder seguir el código y anticipar: event.nombre → María → nombre = María → statusCode 200 → mensaje Hola María. Tu Lambda funciona."}},
{type:"warning",title:"6 · Editar ≠ Deploy ≠ Test",text:"Editar modifica el editor. Deploy actualiza el código de la función. Test provoca una invocación. Si olvidas Deploy, puedes estar probando una versión anterior."},
{type:"steps",title:"7 · Crea tu primer Test Event",steps:[["Test","Abre la zona de eventos de prueba."],["Nombre","Guarda el evento como primer-evento."],["JSON","Utiliza un objeto sencillo con nombre."],["Predice","Antes de ejecutar, explica dónde llegará ese valor."]]},
{type:"code",label:"TEST EVENT",title:"primer-evento",code:"{\n  \"nombre\": \"María\"\n}"},
{type:"concept",title:"8 · Primera invocación",text:"Pulsa Deploy y después Test. El valor María entra por event.nombre y la función devuelve una respuesta. Has ejecutado código en AWS sin administrar directamente un servidor."},
{type:"code",label:"RESULTADO ESPERADO",title:"Respuesta",code:"{\n  \"statusCode\": 200,\n  \"body\": \"{\\\"message\\\":\\\"Hola María. Tu Lambda funciona.\\\"}\"\n}"},
{type:"concept",title:"9 · No te limites a ver verde",text:"Status indica si la invocación terminó; Response muestra lo devuelto; logs explican qué ocurrió; Duration y memoria aportan información de ejecución."},
{type:"steps",title:"10 · CloudWatch Logs",steps:[["Monitor","Entra en Monitor desde la función."],["Logs","Abre los logs asociados en CloudWatch."],["Busca","Localiza Evento recibido y tu JSON."],["Relaciona","Comprueba que ese log pertenece a la invocación que acabas de provocar."]]},
{type:"flow",title:"Dónde termina console.log()",items:["index.mjs","Lambda","console.log()","CloudWatch Logs"]},
{type:"concept",title:"RECUPERAMOS · AWS CLI",text:"La función creada desde la consola también puede observarse desde la CLI. No son dos AWS diferentes: son dos interfaces sobre el mismo recurso."},
{type:"code",label:"GIT BASH",title:"Comprueba la función",code:"aws lambda list-functions"},
{type:"warning",title:"Diagnóstico Academy",text:"Si ayer funcionaba y hoy AWS CLI o una operación falla, comprueba primero aws sts get-caller-identity. Las credenciales de Learning Lab son temporales."},
{type:"checklist",title:"Checkpoint Lambda",items:["He creado ebook-contact.","Entiendo Function e Invocation.","Sé qué son handler y event.","He identificado el Execution Role.","He realizado Deploy antes de Test.","Mi evento devuelve Hola María.","He localizado console.log en CloudWatch.","aws lambda list-functions muestra la función.","Puedo explicar la ejecución sin mirar el código."]},
{type:"quiz",title:"Comprueba",question:"Has cambiado index.mjs, pero Test sigue mostrando el comportamiento anterior. ¿Qué comprobarías primero?",options:["DynamoDB","Que hayas pulsado Deploy","S3","Terraform"],correct:1,explanation:"El editor puede contener cambios que todavía no han sido desplegados a la función."},
{type:"success",title:"He aprendido",text:"Qué significa Serverless en Lambda, qué son Function, Invocation, handler y event, cómo interviene el Execution Role y cómo observar una ejecución en CloudWatch."}
]};